### ISSUE TITLE
Debug `lpdft_HellmanFeynman_grad`

### ISSUE THREAD

**Issue by matthew-hennefarth** [matthew-hennefarth/pyscf-forge#3]
@MatthewRHermes

All work referred to is on the `lpdft-grad` [branch](https://github.com/matthew-hennefarth/pyscf-forge/tree/lpdft-grad).

Currently, I have the simplest test in [grad/test/test_grad_lpdft.py](https://github.com/matthew-hennefarth/pyscf-forge/blob/2d048617819d6bbae5ad5cb2aa8cc87c8cd27911/pyscf/grad/test/test_grad_lpdft.py) which is doing SA(3)-(2e,2o) with H2 using the STO-3G basis set. I have both state-average MC-PDFT and L-PDFT for numerical and analytical gradients so I can ensure my numerical gradients are correct, so that any generalized functions I create in the `/grad/mcpdft.py` are not contributing to any errors, and so I can look at how L-PDFT individual terms compare with the MC-PDFT terms. As expected, MC-PDFT operates normally.

Now, since I am doing SA(3)-(2e,2o) with H2 and the STO-3G basis set, all Lagrange multiplier terms for L-PDFT are negligible. Indeed, the debug statements confirm this as if I look at the log file for what is returned from the [`get_wfn_response`](https://github.com/matthew-hennefarth/pyscf-forge/blob/2d048617819d6bbae5ad5cb2aa8cc87c8cd27911/pyscf/grad/lpdft.py#L308C9-L308C25) function we see that:

```
 g_mo component:
 []
 g_ci component:
 [-4.16333634e-17 -4.37808785e-17 -4.37808785e-17  2.22044605e-16
   1.97215226e-31  9.30224163e-32  9.30224163e-32 -1.97215226e-31
   0.00000000e+00 -2.44703619e-21 -2.44703619e-21  3.38813179e-20]
```

Additionally, the post-L-PDFT Hellmann-Feynmenn term shows that 
```
Orb lagrange hcore component:
[[0. 0. 0.]
 [0. 0. 0.]]
Orb lagrange renorm component:
[[0. 0. 0.]
 [0. 0. 0.]]
Orb lagrange eri component:
[[0. 0. 0.]
 [0. 0. 0.]]
--------------- LINPDFT gradient Lagrange orbital response ---------------
         x                y                z
0 H     0.0000000000     0.0000000000     0.0000000000
1 H     0.0000000000     0.0000000000     0.0000000000
---------------------------------------------------------------------
    CPU time for LINPDFT gradient Lagrange orbital response      0.00 sec, wall time      0.00 sec
--------------- LINPDFT gradient Lagrange response ---------------
         x                y                z
0 H     0.0000000000     0.0000000000     0.0000000000
1 H     0.0000000000     0.0000000000     0.0000000000
----------------------------------------------
```
So any difference between the analytical and numerical gradients should come from the [`lpdft_HellmannFeynman_grad`](https://github.com/matthew-hennefarth/pyscf-forge/blob/2d048617819d6bbae5ad5cb2aa8cc87c8cd27911/pyscf/grad/lpdft.py#L197) function. Now the MC-PDFT Hellmann-Feynmann terms are:

```
MC-PDFT Hellmann-Feynman nuclear:
[[ 1.12011408  0.          0.        ]
 [-1.12011408  0.          0.        ]]
MC-PDFT Hellmann-Feynman hcore component:
[[-1.2302426  0.         0.       ]
 [ 1.2302426  0.         0.       ]]
MC-PDFT Hellmann-Feynman coulomb component:
[[ 0.67751457  0.          0.        ]
 [-0.67751457  0.          0.        ]]
MC-PDFT Hellmann-Feynman xc component:
[[-1.83586138e-01  1.55618715e-18 -1.40890153e-18]
 [ 1.83586138e-01  9.03509088e-18  1.78783076e-18]]
MC-PDFT Hellmann-Feynman quadrature point component:
[[-3.26487891e-01 -6.85790356e-18  8.03165419e-19]
 [ 3.26487891e-01 -3.73337447e-18 -1.18209465e-18]]
MC-PDFT Hellmann-Feynman quadrature weight component:
[[ 3.26565400e-01 -1.29891984e-18 -2.28683451e-19]
 [-3.26565400e-01  1.29891984e-18  2.28683451e-19]]
MC-PDFT Hellmann-Feynman renorm component:
[[ 0.11722217  0.          0.        ]
 [-0.11722217  0.          0.        ]]
```

The L-PDFT Hellmann-Feynman terms are
```
L-PDFT Hellmann-Feynman nuclear:
[[ 1.12011408  0.          0.        ]
 [-1.12011408  0.          0.        ]]
L-PDFT Hellmann-Feynman hcore component:
[[-1.17709613  0.          0.        ]
 [ 1.17709613  0.          0.        ]]
L-PDFT Hellmann-Feynman coulomb component:
[[ 0.6477141  0.         0.       ]
 [-0.6477141  0.         0.       ]]
L-PDFT Hellmann-Feynman xc component:
[[-2.32133866e-01 -1.54025691e-18  1.79877381e-18]
 [ 2.32133866e-01  9.47072817e-19 -3.75687956e-18]]
L-PDFT Hellmann-Feynman quadrature point component:
[[-3.03444134e-01 -1.11280252e-18 -3.14233112e-18]
 [ 3.03444134e-01  1.70598661e-18  5.10043687e-18]]
L-PDFT Hellmann-Feynman quadrature weight component:
[[ 3.03437263e-01  7.49855976e-19 -1.87448527e-18]
 [-3.03437263e-01 -7.49855976e-19  1.87448527e-18]]
L-PDFT Hellmann-Feynman renorm component:
[[ 0.18089957  0.          0.        ]
 [-0.18089957  0.          0.        ]]
```
While this is not super helpful since we cannot really every compare directly L-PDFT and MC-PDFT terms (especially since MC-PDFT still has some Lagrange multiplier terms), it can give us an idea of what we should expect. For example, we should expect that the quadrature point and weight to be very close to each other, and that as the grid gets finer, these terms completely cancel each other out and go to 0. Ultimately, there is nothing egregiously wrong with these terms.

## Nuclear and Core Components
Now, the nuclear and core components should be good for L-PDFT since these don't require too much actual code. 

## The Coulomb Components
The Coulomb term is a bit tricker since in the L-PDFT energy expression, the coulomb terms are

$$
\mathcal{J}^q_p[\check{\gamma}]\gamma^p_q - \frac{1}{2}\mathcal{J}^q_p[\check{\gamma}]\check{\gamma}^p_q
$$

Using the notation in the [Analytical gradients for state-averaged multi configuration pair-density functional theory](dx.doi.org/10.1063/5.0007040), we can write the derivative of the second term as

$$
2\mathcal{J}^q_{\tilde{p}}[\check{\gamma}]\check{\gamma}^p_q
$$

For the first term, we note that we must account for the fact that the derivative index of the Coulomb term must be on a $p$ or $q$. Hence, we have that 

$$
\mathcal{J}^q_p[\check{\gamma}]\gamma^p_q = 2\mathcal{J}^q_{\tilde{p}}[\check{\gamma}]\gamma^p_q + 2\mathcal{J}^q_{\tilde{p}}[\gamma]\check{\gamma}^p_q
$$

Hence the Coulomb component can be written as

$$
2\mathcal{J}^q_{\tilde{p}}[\check{\gamma}]\Delta^p_q + 2\mathcal{J}^q_{\tilde{p}}[\gamma]\check{\gamma}^p_q
$$

Again, I believe I have this term correctly coded up. 

## The Renormalization Component
That leaves the On-Top and the Renormalization terms. For the renormalization term, I extracted the following function from the MC-PDFT Hellmann-Feynman function: [`gfock_sym`](https://github.com/matthew-hennefarth/pyscf-forge/blob/2d048617819d6bbae5ad5cb2aa8cc87c8cd27911/pyscf/grad/mcpdft.py#L34). This should correctly build the L-PDFT generalized Fock components since both the on-top potentials and the on-top gradient response terms have the same type of symmetry. Hence I build the `dme0` term as ([in context](https://github.com/matthew-hennefarth/pyscf-forge/blob/2d048617819d6bbae5ad5cb2aa8cc87c8cd27911/pyscf/grad/lpdft.py#L224-L229))

```python
    # Generate the Generalized Fock Component
    gfock_expl = mcpdft_grad.gfock_sym(mc, mo_coeff, casdm1, casdm2, mc.get_lpdft_hcore(), mc.veff2)
    gfock_impl = mcpdft_grad.gfock_sym(mc, mo_coeff, casdm1_0, casdm2_0, feff1, feff2)
    gfock = gfock_expl + gfock_impl


    dme0 = mo_coeff @ (0.5 * (gfock + gfock.T)) @ mo_coeff.T
```
Note: the `feff1` term includes the Coulomb interaction with the $\Delta$ density (similar to `veff1` in MC-PDFT). Also, I generate the `feff1, feff2` terms with [this function](https://github.com/matthew-hennefarth/pyscf-forge/blob/2d048617819d6bbae5ad5cb2aa8cc87c8cd27911/pyscf/grad/lpdft.py#L381-L411). It might be possible that there is an error in my reasoning or code which is causing this term to be different from what it should be (especially since it deviates fairly largely from the MC-PDFT renormalization term). Perhaps I can confirm I am building the correct `delta` density to contract the `fot` terms with? Did I overlook something in building the `gfock` term?

## XC, Grid, and Weight
This is the one I truly am unsure if I did correctly since it is a bit of a mess to do right. I put all of this into the [`get_ontop_response`](https://github.com/matthew-hennefarth/pyscf-forge/blob/2d048617819d6bbae5ad5cb2aa8cc87c8cd27911/pyscf/grad/lpdft.py#L37) function to make my life easier and for better code readability? I try and make sure to separate the `cas_natorb` for the state and the state-average density (see [here](https://github.com/matthew-hennefarth/pyscf-forge/blob/2d048617819d6bbae5ad5cb2aa8cc87c8cd27911/pyscf/grad/lpdft.py#L55-L56)) since this matters inside the loop. I also extracted [this function](https://github.com/matthew-hennefarth/pyscf-forge/blob/2d048617819d6bbae5ad5cb2aa8cc87c8cd27911/pyscf/grad/mcpdft.py#L68) which actually gets the `tmp_dv` term as it is called in MC-PDFT. I am fairly confident that I am generating the grid and weight components correctly (if I am generating the `tmp_dv` term as it is a straightforward implementation. 

I have attached my [L_PDFT_Nuclear_Gradients](https://github.com/matthew-hennefarth/pyscf-forge/files/12811000/L_PDFT_Nuclear_Gradients.pdf) pdf for you to see the relevant equation (and maybe I made an arithmetic mistake! But I don't think so since the equations reduce to SS-PDFT gradients in the limit of 1 state). 

Honestly, any help would be appreciated. Sorry, and I know that this is a lot.

**Comment by MatthewRHermes** [comment]
So I started playing around with it and I stumbled on something: if you change the internuclear distance to 2.5 or higher, you SOMETIMES get agreement:
```
0.013660994794918224
[[-1.36609948e-02 -2.82616582e-21  4.90702420e-20]
 [ 1.36609948e-02 -1.10045395e-21  3.60148565e-21]]
3.34223499570685e-11 # <- printed the difference for convenience
LPDFT STUFF NOW
[[-1.00000000e+00 -2.47639350e-15] # <- printed lpdft.ci[0] for reasons that will become clear below
 [-2.47639350e-15 -1.04475543e-15]]
[-0.73217857 -0.68429252 -0.63640648]
0.07524766941787675
WARN: Active orbitals [0] (occs = [2.]) are canonicalized with core orbitals
WARN: Active orbitals [1] (occs = [2.1830278e-30]) are canonicalized with external orbitals
[[-7.52476695e-02 -5.50226974e-21 -1.22050347e-20]
 [ 7.52476695e-02  1.50061902e-21  4.98705721e-20]]
3.515819579913426e-11 # <- printed the difference for convenience
.
----------------------------------------------------------------------
Ran 1 test in 10.999s

OK
```
But other times, you don't:
```
0.013660994794918224
[[-1.36609949e-02 -3.02624836e-21  4.83699531e-20]
 [ 1.36609949e-02 -1.10045395e-21  3.60148565e-21]]
5.53451486029477e-11 # <- printed the difference for convenience
LPDFT STUFF NOW
[[-1.88841475e-01  4.26240744e-15] # <- printed lpdft.ci[0]
 [ 4.26240744e-15  9.82007585e-01]]
[-0.73217857 -0.68429252 -0.63640648]
0.07524766944698058
[[ 8.10163081e-02  1.51062315e-20  1.74572013e-20]
 [-8.10163081e-02 -1.87077171e-20 -6.10751941e-20]]
0.005768638626780037 # <- printed the difference for convenience
.
----------------------------------------------------------------------
Ran 1 test in 11.822s

OK
```
The difference appears to be in the orbital canonicalization: the state-averaged natural orbitals are underdefined since the state-averaged occupancy is [1,1] when you trace over the whole Hilbert space. The wave function is "really" single-determinantal, and when the natorbs land on the appropriate frame to see this ground state's single-configurational nature, the analytical computed gradient is correct. In the logfiles for these two calculations, _every single component_ other than the nuclear-nuclear terms differ.

**Comment by matthew-hennefarth** [comment]
Seems to be I was stupid and didn't know how to compute the CI vectors for the L-PDFT states...
