### ISSUE TITLE
Debug L-PDFT `get_wfn_response` and `lpdft_HellmanFeynman_grad `

### ISSUE THREAD

**Issue by matthew-hennefarth** [matthew-hennefarth/pyscf-forge#9]
First, lets try and debug the [`lpdft_HellmanFeynman_grad`](https://github.com/matthew-hennefarth/pyscf-forge/blob/5908095a88a9db3ab0af2e847723b84d098561d6/pyscf/grad/lpdft.py#L197) function.

## H2 SA(10) (4e, 2o) with 6-31G Basis
H2 distance is 1.2 and `tLDA,VWN3` functional. Now, both CI and MO Lagrange multipliers are negligible. So only difference should come from [`lpdft_HellmanFeynman_grad`](https://github.com/matthew-hennefarth/pyscf-forge/blob/5908095a88a9db3ab0af2e847723b84d098561d6/pyscf/grad/lpdft.py#L197) function. Indeed
```
g_mo component:
[]
```
and the `g_ci` is 0.

Using a $\delta=0.02$, the error between the analytic and numerical gradients is
```
[3.24780878e-06 7.82124112e-06 1.23946734e-05
 2.10347566e-05 2.46251004e-05 2.56081890e-05
 2.91985327e-05 3.88217046e-05 4.24120483e-05
 4.60023921e-05]
```
Comparing the MC-PDFT at the same geometry (error between analytic and numerical gradients)
```
[-2.52915076e-05 -3.29904077e-05  2.15945357e-05
  1.56598897e-04  8.32699945e-05  1.29123291e-04
  2.97017537e-05 -4.30061998e-05  3.15464518e-05
  1.49408787e-04]
```
I am fairly confident that the [`lpdft_HellmanFeynman_grad`](https://github.com/matthew-hennefarth/pyscf-forge/blob/5908095a88a9db3ab0af2e847723b84d098561d6/pyscf/grad/lpdft.py#L197) function. is debugged (minus any problem due to core orbitals...)

**Comment by matthew-hennefarth** [comment]
Assuming that the [`lpdft_HellmanFeynman_grad`](https://github.com/matthew-hennefarth/pyscf-forge/blob/5908095a88a9db3ab0af2e847723b84d098561d6/pyscf/grad/lpdft.py#L197) function is debugged, we turn now to [`get_wfn_response`](https://github.com/matthew-hennefarth/pyscf-forge/blob/5908095a88a9db3ab0af2e847723b84d098561d6/pyscf/grad/lpdft.py#L308).

## H2 SA(3) (2e,2o) with 6-31G Basis
H2 distance is 1.2 and `tLDA,VWN3` functional. Now the CI Lagrange multiplier should be negligible, but the MO component is not. We see that this is true as
```
g_mo component:
[-1.20049326e-01 -6.36330964e-16 -2.12345838e-16 -4.33028043e-02]
g_ci component:
[ 3.32215426e-33 -1.16785238e-22  1.16785238e-22  2.46519033e-32
  0.00000000e+00  2.31111593e-32  1.07852077e-32  0.00000000e+00
  1.15555797e-33 -1.94114382e-19  1.94114382e-19  1.60531780e-32]
```

Using a $\delta=0.02$ the error between analytic and numerical gradients is
```
[2.40650433e-06 7.10763467e-06 1.18087650e-05]
```
Comparing with the MC-PDFT error:
```
[2.76939180e-06 7.79260331e-06 1.43483541e-05]
```
It seems that the MO Lagrange terms do not seem to raise any issue.

## H2 SA(3) (2e, 4o) with 6-31G Basis
H2 distance is 1.2 and `tLDA,VWN3` functional. Now the CI Lagrange multipliers are not negligible, but the MO is. Indeed, we see that
```
g_mo component:
[]
```
and the `g_ci` is not necessarily 0. 

Using a $\delta=0.02$, the error between analytic and numerical gradients is 
```
[-3.96796106e-04 -4.22017240e-05 -1.53077925e-03]
```
whereas if we compare to MC-PDFT it is
```
[-2.52915907e-05 -3.29904103e-05  2.15945531e-05]
```
This error for L-PDFT persists across all functionals, whereas MC-PDFT has a much better error of ~1e-6. 

I suspect there is an issue with how we are generating `g_ci` and this needs to be looked at in more detail. Perhaps it has to do with the projection? Or maybe the `A_op` thing that I hoped I wouldn't have to have touched...

**Comment by matthew-hennefarth** [comment]
It shouldn't make sense that the `A_op` should matter since that only removes SA-SA rotations from the `Ax` term. These are also redundant in L-PDFT. I also don't think the Lagrange optimizer is throwing away the sector of CI values which should be zero in CASSCF, MC-PDFT, and other MS-PDFT methods since it still needs to solve the Lagrange multiplier terms in that sector. But maybe the Pre-conditioner is doing something in this sector? Might need to take a look there.

## H2 SA(4) (2e,4o) with 6-31G Basis
As before, but just bumping the SA to 4 causes the L-PDFT error to be much worse:
```
[ 0.00129624 -0.0006063   0.00131681 -0.00366912]
```
whereas the MC-PDFT error is decent at 
```
[-2.52915268e-05 -3.29904128e-05  2.15945821e-05  1.56598897e-04]
```

**Comment by matthew-hennefarth** [comment]
I can't seem to see anything necessarily wrong with the `wfn_response` function, and have a feeling that this has to do with the `lpdft_HellmanFeynman_grad` function. Looking at MC-PDFT when I use a grid of 1 and 6 I see that the quadrature and grid goes as
```
# Grid of 1
MC-PDFT Hellmann-Feynman xc component:
[[-1.40486983e-01 -2.53984897e-18 -8.92398077e-18]
 [ 1.40486983e-01  1.20249377e-18 -5.89371276e-18]]
MC-PDFT Hellmann-Feynman quadrature point component:
[[-1.28425521e-01  3.54887129e-18  7.82527146e-18]
 [ 1.28425521e-01 -2.21151610e-18  6.99242207e-18]]
MC-PDFT Hellmann-Feynman quadrature weight component:
[[ 1.28375098e-01 -1.86334675e-20 -1.17634502e-19]
 [-1.28375098e-01  1.86334675e-20  1.17634502e-19]]
```
```
# Grid of 6
MC-PDFT Hellmann-Feynman xc component:
[[-1.40455379e-01  8.65481999e-20 -6.57480454e-19]
 [ 1.40455379e-01 -7.43505393e-19  1.39227615e-18]]
MC-PDFT Hellmann-Feynman quadrature point component:
[[-1.28389293e-01  9.50828381e-19  1.81322719e-18]
 [ 1.28389293e-01  4.07677855e-19 -4.11829310e-18]]
MC-PDFT Hellmann-Feynman quadrature weight component:
[[ 1.28386343e-01 -1.77876919e-20  1.22502140e-19]
 [-1.28386343e-01  1.77876919e-20 -1.22502140e-19]]
```
whereas for L-PDFT it is
```
# Grid of 1
L-PDFT Hellmann-Feynman xc component:
[[-1.72591244e-01  3.73014336e-18 -3.03607997e-18]
 [ 1.72591244e-01 -1.56650619e-18 -7.00234598e-19]]
L-PDFT Hellmann-Feynman quadrature point component:
[[-1.23852225e-01 -2.57284055e-19  1.60984044e-18]
 [ 1.23852225e-01 -1.90635312e-18  2.12647413e-18]]
L-PDFT Hellmann-Feynman quadrature weight component:
[[ 1.26509736e-01 -6.49816133e-20  3.62712639e-19]
 [-1.26509736e-01  6.49816133e-20 -3.62712639e-19]]
```
```
# Grid of 6
L-PDFT Hellmann-Feynman xc component:
[[-1.72284510e-01  5.31409386e-19 -4.23865541e-19]
 [ 1.72284510e-01  3.36370257e-19  2.56961657e-18]]
L-PDFT Hellmann-Feynman quadrature point component:
[[-1.23658384e-01 -1.39809344e-18  9.49567569e-19]
 [ 1.23658384e-01  5.30313795e-19 -3.09531860e-18]]
L-PDFT Hellmann-Feynman quadrature weight component:
[[ 1.26480701e-01 -3.27801751e-19  1.23805777e-18]
 [-1.26480701e-01  3.27801751e-19 -1.23805777e-18]]
```
Notice that the quadrature point and weight components do not being to cancel each other out as they should. So I believe there is still an issue with my quadrature term. Might need to check `vot_contract` or the `cas_natorb` function stuff..

**Comment by matthew-hennefarth** [comment]
@MatthewRHermes The [test](https://github.com/matthew-hennefarth/pyscf-forge/blob/7b2f8143a7817ee8a55ec0dc180ad34a7ee0bdec/pyscf/grad/test/test_grad_lpdft.py#L75-L99) of H2 6-31G SA(4)-(2e,4o) seems to be failing. I am not sure if it is the CI Lagrange multiplier or if the XC of the Hellman-Feynman function is wrong. I suspect the Hellman-Feynman function is wrong given that [the point and weight terms are very different as compared to MC-PDFT](https://github.com/matthew-hennefarth/pyscf-forge/issues/9#issuecomment-1751101175). 

I think I take care of projecting out the model-space from the CI wfn terms [here](https://github.com/matthew-hennefarth/pyscf-forge/blob/7b2f8143a7817ee8a55ec0dc180ad34a7ee0bdec/pyscf/grad/lpdft.py#L357-L372). I don't bother updating the `my_Aop` since that should be the same as SA-CASSCF (my understanding). The initial guess should also be the same as in SA-CASSCF. Thoughts? Things I should check?

**Comment by MatthewRHermes** [comment]
Switch to ftLDA and the quadrature points and weights cancel each other much more closely, but the error is about the same:
```
(pyscf) herme068@herme068:test$ python test_grad_lpdft.py ; grep -A5 "L-PDFT Hellmann-Feynman quadrature point component:" lpdft.log 
/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
Full Tests for L-PDFT gradients API
overwrite output file: lpdft.log
/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/h5py/_hl/dataset.py:541: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  arr = numpy.ndarray(selection.mshape, dtype=new_dtype)
WARN: Large deviations found between the input molecule and the molecule from chkfile
Initial guess density matrix may have large error.
WARN: Large deviations found between the input molecule and the molecule from chkfile
Initial guess density matrix may have large error.
WARN: Large deviations found between the input molecule and the molecule from chkfile
Initial guess density matrix may have large error.
[-0.00050274 -0.00024021 -0.00026589 -0.00049534]
.
----------------------------------------------------------------------
Ran 1 test in 4.307s

OK
L-PDFT Hellmann-Feynman quadrature point component:
[[-1.26439682e-01 -1.23507429e-18  2.34344883e-18]
 [ 1.26439682e-01 -1.72888169e-20  2.54496178e-19]]
L-PDFT Hellmann-Feynman quadrature weight component:
[[ 1.26465602e-01 -1.96511644e-19 -8.13151629e-20]
 [-1.26465602e-01  1.96511644e-19  8.13151629e-20]]
--
L-PDFT Hellmann-Feynman quadrature point component:
[[-6.40998612e-02  4.04687765e-19 -1.21689575e-19]
 [ 6.40998612e-02 -6.40430943e-21  1.53617307e-18]]
L-PDFT Hellmann-Feynman quadrature weight component:
[[ 6.40544494e-02  9.19877781e-19  7.45388994e-20]
 [-6.40544494e-02 -9.19877781e-19 -7.45388994e-20]]
--
L-PDFT Hellmann-Feynman quadrature point component:
[[-5.41996376e-03 -1.68621131e-19  1.18501134e-18]
 [ 5.41996376e-03 -6.26290817e-20 -9.05031229e-19]]
L-PDFT Hellmann-Feynman quadrature weight component:
[[ 5.41260066e-03  2.40874994e-20  2.20228566e-20]
 [-5.41260066e-03 -2.40874994e-20 -2.20228566e-20]]
--
L-PDFT Hellmann-Feynman quadrature point component:
[[-7.69947736e-02 -1.07224065e-18 -2.70353537e-20]
 [ 7.69947736e-02  7.90470164e-19 -8.36921348e-19]]
L-PDFT Hellmann-Feynman quadrature weight component:
[[ 7.70189577e-02 -3.98105485e-20  4.74338450e-20]
 [-7.70189577e-02  3.98105485e-20 -4.74338450e-20]]
```

**Comment by matthew-hennefarth** [comment]
> Switch to ftLDA and the quadrature points and weights cancel each other much more closely, but the error is about the same:

Guess that points still to then the CI Lagrange Term/Optimization step. Hm. Does the Lagrange solver do anything for the fact that, for CASSCF, and MC-PDFT that 

$$
\frac{\partial E_\Gamma}{\partial P^\perp_{\Lambda M}} = 2\delta_{\Gamma \Lambda}H_\Lambda^M
$$

That is, is there any optimization for the sector where $\Gamma \neq \Lambda$ the derivative is zero?

**Comment by MatthewRHermes** [comment]
I'm not sure I understand the question, but the $\Lambda M$, $\Gamma \neq \Lambda$ sector of the Lagrange multipliers are populated by the SA-CASSCF Hessian, even though the gradient is zero.

**Comment by MatthewRHermes** [comment]
I think you will have to incorporate [some of this stuff](https://github.com/matthew-hennefarth/pyscf-forge/blob/lpdft-grad/pyscf/grad/mspdft.py#L378-L408). The `*_is*`, `d2f`, and `diab_response` stuff doesn't apply to you, but I think the `ham_od` stuff does. If your CI vectors aren't MC-SCF eigenstates then `newton_casscf.gen_g_hop` misses some stuff in the Hessian-vector product.

**Comment by matthew-hennefarth** [comment]
Thanks, I will look through that routine and see what makes sense.

**Comment by matthew-hennefarth** [comment]
@MatthewRHermes I think that might have done the trick! Using this
```python
  def get_Aop_Adiag(self, verbose=None, mo=None, ci=None, eris=None, state=None, **kwargs):
      if verbose is None:
          verbose = self.verbose

      if mo is None:
          mo = self.base.mo_coeff

      if ci is None:
          ci = self.base.ci

      if state is None:
          state = self.state

      if eris is None and self.eris is None:
          eris = self.eris = self.base.ao2mo(mo)

      elif eris is None:
          eris = self.eris

      ham_od = mspdft.make_heff_mcscf(self.base, mo_coeff=mo, ci=ci)
      ham_od[np.diag_indices_from(ham_od)] = 0.0
      ham_od += ham_od.T  # This corresponds to the arbitrary newton_casscf*2
      fcasscf = self.make_fcasscf_sa()

      hop, Adiag = newton_casscf.gen_g_hop (fcasscf, mo, ci, eris, verbose)[2:]

      def Aop(x):
          Ax = hop(x)
          x_c = self.unpack_uniq_var (x)[1]
          Ax_o, Ax_c = self.unpack_uniq_var(Ax)
          Ax_c = mspdft_grad.Gradients._separate_is_component(self, Ax_c)[0]
          Ax_c_od = list (np.tensordot (-ham_od, np.stack (x_c, axis=0),
              axes=1))
          Ax_c = [a1 + (w*a2) for a1, a2, w in zip (Ax_c, Ax_c_od,
              self.base.weights)]
          return self.pack_uniq_var(Ax_o, Ax_c)

      return Aop, Adiag
```
and this setup for testing numerical gradients

```
    def test_h2_631g(self):
        nstates = 4
        for fnal in ('tLDA,VWN3', 'ftLDA,VWN3', 'tPBE', 'ftPBE'):
            with self.subTest(nstates=nstates, fnal=fnal):
                mc = mcpdft.CASSCF(h2_631g, fnal, 4, 2, grids_level=1)
                mc.fix_spin_(ss=0, shift=2)
                mc.conv_tol=1e-10
                mc.conv_grad_tol=1e-10
                #lpdft = mc.state_average([1.0 / nstates, ] * nstates).run()
                lpdft = mc.multi_state([1.0 / nstates, ] * nstates, method='lin').run()
                lpdft_grad = lpdft.nuc_grad_method()

                de = np.zeros(nstates)
                for state in range(nstates):
                    de[state] = lpdft_grad.kernel(state=state)[1, 0]

                lscanner = lpdft.as_scanner()
                mol = lpdft.mol
                lscanner(mol.set_geom_('H 0 0 0; H 1.2001 0 0'))
                e1 = np.array(lscanner.e_states)
                lscanner(mol.set_geom_('H 0 0 0; H 1.1999 0 0'))
                e2 = np.array(lscanner.e_states)
                lscanner(mol.set_geom_(h2_xyz))  # reset
                de_ref = (e1 - e2) / 0.0002 * lib.param.BOHR
                print(de-de_ref)
                return
```
I get an error of `[3.17234042e-06 -2.98802772e-04  2.31735078e-06 -4.04065518e-06]`! And, this error started to actually decrease as I changed the numerical gradient. I will now do some convergence checks of numerical vs analytical gradients for this system/basis set/lagrange terms to see how it performs!
